/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.6
 * Generated at: 2016-11-17 00:36:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class consultaHistorica_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/Users/APerez/Documents/workspace-for-sts/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/web/WEB-INF/lib/spring-webmvc-4.3.3.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1474314770000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.3.3.RELEASE.jar", Long.valueOf(1477501503367L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1477501505027L));
    _jspx_dependants.put("jar:file:/C:/Users/APerez/Documents/workspace-for-sts/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/web/WEB-INF/lib/spring-webmvc-4.3.3.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1474314770000L));
    _jspx_dependants.put("jar:file:/C:/Users/APerez/Documents/workspace-for-sts/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/web/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153403082000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>Welcome</title>\r\n");
      out.write("    <!-- JQuery UI -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css\">\r\n");
      out.write("    <!-- Bootstrap -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css\">\r\n");
      out.write("\t<!-- DataTables -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/web/resource/css/datatables.min.css\"/>\r\n");
      out.write("\t<!-- Highcharts -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/web/resource/css/highcharts.css\">\r\n");
      out.write("\t<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/web/resource/css/ie10-viewport-bug-workaround.css\">\r\n");
      out.write("    \r\n");
      out.write("\t<!-- JQuery & JQuery UI javascript-->\r\n");
      out.write("\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\r\n");
      out.write("  \t<script src=\"https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js\"></script>\r\n");
      out.write("  \t\r\n");
      out.write("    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->\r\n");
      out.write("    <!--[if lt IE 9]><script src=\"/web/resource/js/ie8-responsive-file-warning.js\"></script><![endif]-->\r\n");
      out.write("    <script src=\"/web/resource/js/ie-emulation-modes-warning.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js\"></script>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("    <style>\r\n");
      out.write("    \t.st80{\r\n");
      out.write("\t\t\twidth: 80%;\r\n");
      out.write("\t\t\tmargin: 0 auto;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.row{\r\n");
      out.write("\t\t\tpadding-top: 10px;\r\n");
      out.write("\t\t\tpadding-bottom: 10px;\r\n");
      out.write("\t\t}\r\n");
      out.write("    \tdiv.generateReport{\r\n");
      out.write("\t\t\twidth: 60%;\r\n");
      out.write("\t\t\tdisplay: block;\r\n");
      out.write("\t\t\tbackground-color: #4682B4;\r\n");
      out.write("\t\t\tcolor: #FFFFFF;\r\n");
      out.write("\t\t\tfont-weight: 600;\r\n");
      out.write("\t\t\tpadding: 10px 0 10px 10px;\r\n");
      out.write("    \t\tmargin: 10px 0;\r\n");
      out.write("    \t\tborder-radius: 5px;\r\n");
      out.write("    \t\tborder: 2px solid #4682B4;\r\n");
      out.write("    \t\ttransition: all 500ms ease;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdiv.generateReport:hover{\r\n");
      out.write("\t\t\tbackground-color: #0c3a61;\r\n");
      out.write("\t\t\tborder: 2px solid #0c3a61;\r\n");
      out.write("\t\t\tcursor: pointer;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdiv#highcharts-0{\r\n");
      out.write("\t\t\theight: 350px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdiv#highcharts-0 svg{\r\n");
      out.write("\t\t\theight: 100%;\r\n");
      out.write("\t\t\twidth: 100%;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdiv.col-sm-3 > div.st80 > input[type=\"text\"],\r\n");
      out.write("\t\tdiv.col-sm-3 > div.st80 > select{\r\n");
      out.write("\t\t\twidth: 85%;\r\n");
      out.write("\t\t}\r\n");
      out.write("    </style>\r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("\t    function Options(){\r\n");
      out.write("\t\t\tthis.id_proveedor = 0;\r\n");
      out.write("\t\t\tthis.id_factor = 0;\r\n");
      out.write("\t\t\tthis.fechaI = \"\";\r\n");
      out.write("\t\t\tthis.fechaF = \"\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t    \r\n");
      out.write("\t    Options.prototype.equals = function(n){\r\n");
      out.write("\t\t\tif(this.id_proveedor != n.id_proveedor){ return false;}\r\n");
      out.write("\t\t\tif(this.id_factor != n.id_factor){ return false;}\r\n");
      out.write("\t\t\tif(this.fechaI != n.fechaI){ return false;}\r\n");
      out.write("\t\t\tif(this.fechaF != n.fechaF){ return false;}\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t    \r\n");
      out.write("\t    var $enableDestroy = 0;\r\n");
      out.write("\t    var sels = new Options();\r\n");
      out.write("\t    var dataTable;\r\n");
      out.write("\t    \r\n");
      out.write("\t    function drawGraphics(){\r\n");
      out.write("\t\t\tvar chart = new Highcharts.Chart({\r\n");
      out.write("                chart: {\r\n");
      out.write("                \trenderTo: 'graphic',\r\n");
      out.write("                    type: 'line',\r\n");
      out.write("                    borderWidth: 1,\r\n");
      out.write("                    plotBorderWidth: 2,\r\n");
      out.write("                    borderColor: '#a1a1a1',\r\n");
      out.write("                    borderRadius: 3,\r\n");
      out.write("                    marginLeft: 80\r\n");
      out.write("                },\r\n");
      out.write("                data: {\r\n");
      out.write("                    table: 'tableReport'\r\n");
      out.write("                },\r\n");
      out.write("                title: {\r\n");
      out.write("                    text: 'TEMP'\r\n");
      out.write("                },\r\n");
      out.write("                legend: {\r\n");
      out.write("                    enabled: false\r\n");
      out.write("                },\r\n");
      out.write("                xAxis: {\r\n");
      out.write("                    showLastLabel: true,\r\n");
      out.write("                    tickPixelInterval: 25,\r\n");
      out.write("                    type: 'datetime',\r\n");
      out.write("                    labels: {\r\n");
      out.write("                        format: '{value:%d-%m-%y}',\r\n");
      out.write("                        rotation: 90,\r\n");
      out.write("                        style: {\r\n");
      out.write("                            fontSize: '1.2em'\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                yAxis: {  \r\n");
      out.write("                    title: {\r\n");
      out.write("                        enabled: false\r\n");
      out.write("                    },\r\n");
      out.write("                    labels: {\r\n");
      out.write("                        format: '{value} %',\r\n");
      out.write("                        style: { fontSize: '1.2em' }\r\n");
      out.write("                    },\r\n");
      out.write("                    tickPixelInterval: 80\r\n");
      out.write("                },\r\n");
      out.write("                credits: {\r\n");
      out.write("                    enabled: false\r\n");
      out.write("                },\r\n");
      out.write("                plotOptions: {\r\n");
      out.write("                    series: {\r\n");
      out.write("                        dataLabels: {\r\n");
      out.write("                            enabled: true,\r\n");
      out.write("                            format: '{point.label}'\r\n");
      out.write("                        },\r\n");
      out.write("                        tooltip: {\r\n");
      out.write("                            valueSuffix: ' %'\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                tooltip: {\r\n");
      out.write("                    pointFormat: '<span style=\"color:{series.color}\">{series.name}</span>: <b>{point.y}</b> ({point.change}%)<br/>',\r\n");
      out.write("                    valueDecimals: 2\r\n");
      out.write("                }\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t    \r\n");
      out.write("\t    function drawTables() {\r\n");
      out.write("            dataTable = $('#tableReport').DataTable({\r\n");
      out.write("                \"bSort\" :          false,\r\n");
      out.write("                \"sPaginationType\": \"full_numbers\"\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        function deleteTables(){\r\n");
      out.write("            dataTable.destroy();\r\n");
      out.write("        }\r\n");
      out.write("\t    \r\n");
      out.write("\t    function getFactores(sel) {\r\n");
      out.write("\t    \tsels.id_proveedor = sel.value;\r\n");
      out.write("\t\t\tajaxFactorFunction(sel.value);\r\n");
      out.write("\t    }\r\n");
      out.write("\t    \r\n");
      out.write("\t    function generateReport(){\r\n");
      out.write("\t    \tsels.id_factor = $('#selFactor').val();\r\n");
      out.write("\r\n");
      out.write("\t\t\tajaxReportFunction();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t    \r\n");
      out.write("\t    function ajaxFactorFunction(id){\r\n");
      out.write("\t    \t$.ajax({\r\n");
      out.write("            \turl : 'consultaHistorica/factores/'+id,\r\n");
      out.write("            \tcache : false,\r\n");
      out.write("                contentType : 'application/json; charset=utf-8',\r\n");
      out.write("                type : 'GET',\r\n");
      out.write("            \tsuccess : function(data) {\r\n");
      out.write("            \t\tvar items = [];\r\n");
      out.write("            \t\t\r\n");
      out.write("            \t\t$.each(data, function(id, option){\r\n");
      out.write("            \t\t\titems.push(\"<option value='\"+ option.id_factor +\"' \" \r\n");
      out.write("            \t\t\t\t\t  + \"name='\" + option.id_proveedor + \"' \"\r\n");
      out.write("            \t\t\t\t\t  + \">\" + option.factor + \"</option>\");\r\n");
      out.write("            \t\t});\r\n");
      out.write("            \t\t\r\n");
      out.write("            \t\t$('#selFactor').html('');\r\n");
      out.write("            \t\t$('#selFactor').html(items.join(''));\r\n");
      out.write("            \t}\r\n");
      out.write("\t    \t});\r\n");
      out.write("\t    }\r\n");
      out.write("\t    \r\n");
      out.write("\t    function ajaxReportFunction(){\r\n");
      out.write("\t    \t$.ajax({\r\n");
      out.write("\t\t    \turl : 'consultaHistorica/report/',\r\n");
      out.write("\t\t       \tcache : false,\r\n");
      out.write("\t           \tcontentType : 'application/json; charset=utf-8',\r\n");
      out.write("\t           \tdataType : 'json',\r\n");
      out.write("\t           \tdata : JSON.stringify(sels),\r\n");
      out.write("\t           \ttype : 'POST',\r\n");
      out.write("\t\t       \tsuccess : function(data){\r\n");
      out.write("\t\t       \t\tvar report = [];\r\n");
      out.write("\t\t       \t\tvar div = \"<div class='col-sm-6 col-xs-12'><div id='graphic'></div></div>\";\r\n");
      out.write("\t\t       \t\tvar info = \"<div class='col-sm-6 col-xs-12'><div class='st80'><table id='tableReport'><thead>\"\r\n");
      out.write("\t\t       \t\t\t\t + \"<tr><th>Fecha</th><th>Valor</th></tr>\"\r\n");
      out.write("\t\t       \t\t\t\t + \"</thead>\"\r\n");
      out.write("\t\t       \t\t\t\t + \"<tbody>\";\r\n");
      out.write("\t\t       \t\t\r\n");
      out.write("\t\t       \t\t$.each(data, function(id, option){\r\n");
      out.write("\t\t       \t\t\tconsole.log(option.date);\r\n");
      out.write("\t\t       \t\t\tinfo += \"<tr><td>\" + option.date + \"</td><td>\" + option.doubleValue + \"</td></tr>\";\r\n");
      out.write("\t\t       \t\t});\r\n");
      out.write("\t\t       \t\t\r\n");
      out.write("\t\t       \t\tinfo += \"</tbody></table></div></div>\";\r\n");
      out.write("\t\t       \t\treport.push(div);\r\n");
      out.write("\t\t       \t\treport.push(info);\r\n");
      out.write("\t\t       \t\t\r\n");
      out.write("\t\t       \t\tif( $enableDestroy > 0 ){\r\n");
      out.write("\t                    deleteTables();\r\n");
      out.write("\t                }\r\n");
      out.write("\t\t       \t\t$('#report').html(report.join(''));\r\n");
      out.write("\t\t       \t\tdrawGraphics();\r\n");
      out.write("\t\t       \t\tdrawTables();\r\n");
      out.write("\t\t       \t\t$enableDestroy = $enableDestroy + 1;\r\n");
      out.write("\t\t       \t}\r\n");
      out.write("\t    \t});\r\n");
      out.write("\t    }\r\n");
      out.write("\t    \r\n");
      out.write("    \t$(function(){\r\n");
      out.write("    \t\t$(\"#fechaI\").datepicker({\r\n");
      out.write("\t\t\t\tshowOn          : \"button\",\r\n");
      out.write("                buttonImage     : \"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\",\r\n");
      out.write("                buttonImageOnly : true,\r\n");
      out.write("                buttonText      : \"Seleccione una fecha\",\r\n");
      out.write("                changeMonth     : true,\r\n");
      out.write("                changeYear      : true,\r\n");
      out.write("                yearRange       : \"-15:+0\",\r\n");
      out.write("                dateFormat      : 'mm-dd-yy',\r\n");
      out.write("                showAnim        : 'slideDown',\r\n");
      out.write("                beforeShow      : function(){$(\".ui-datepicker\").css('font-size',10);},\r\n");
      out.write("                onSelect\t\t: function(){sels.fechaI = $(this).val();}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#fechaF\").datepicker({\r\n");
      out.write("\t\t\t\tshowOn          : \"button\",\r\n");
      out.write("\t\t\t\tbuttonImage     : \"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\",\r\n");
      out.write("                buttonImageOnly : true,\r\n");
      out.write("                buttonText      : \"Seleccione una fecha\",\r\n");
      out.write("                changeMonth     : true,\r\n");
      out.write("                changeYear      : true,\r\n");
      out.write("                yearRange       : \"-15:+0\",\r\n");
      out.write("                dateFormat      : 'mm-dd-yy',\r\n");
      out.write("                showAnim        : 'slideDown',\r\n");
      out.write("                beforeShow      : function(){$(\".ui-datepicker\").css('font-size',10);},\r\n");
      out.write("                onSelect\t\t: function(){sels.fechaF = $(this).val();}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("    \t});\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<section>\r\n");
      out.write("\t\t<div class=\"container jumbotron\">\r\n");
      out.write("\t\t\t<h1> Consulta Histórica </h1>\r\n");
      out.write("\t\t</div><!-- .container end -->\r\n");
      out.write("\t</section>\r\n");
      out.write("\t\r\n");
      out.write("\t<section class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-sm-3 col-xs-12\"><div class=\"st80\">\r\n");
      out.write("\t\t\t\t<label for=\"selProveedor\">Proveedor</label><br>\r\n");
      out.write("\t\t\t\t<select id=\"selProveedor\" onchange=\"getFactores(this);\">\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</div></div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"col-sm-3 col-xs-12\"><div class=\"st80\">\r\n");
      out.write("\t\t\t\t<label for=\"selFactor\">Factor</label><br>\r\n");
      out.write("\t\t\t\t<select id=\"selFactor\">\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</div></div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"col-sm-3 col-xs-12\"><div class=\"st80\">\r\n");
      out.write("\t\t\t\t<label for=\"fechaI\">Fecha inicial</label><br>\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"fechaI\" >\r\n");
      out.write("\t\t\t</div></div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"col-sm-3 col-xs-12\"><div class=\"st80\">\r\n");
      out.write("\t\t\t\t<label for=\"fechaF\">Fecha final</label><br>\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"fechaF\" >\r\n");
      out.write("\t\t\t</div></div>\r\n");
      out.write("\t\t</div><!-- .row end -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-sm-3 col-xs-12\"></div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-3 col-xs-12\"></div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-3 col-xs-12\"></div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-3 col-xs-12\"><div class=\"st80\">\r\n");
      out.write("\t\t\t\t<div class=\"generateReport\" onclick=\"generateReport();\">Enviar</div>\r\n");
      out.write("\t\t\t</div></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"report\" class=\"row\"></div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</section><!-- .container end -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Bootstrap core JavaScript\r\n");
      out.write("\t================================================== -->\r\n");
      out.write("    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/web/resource/js/ie10-viewport-bug-workaround.js\"></script>\r\n");
      out.write("    <!-- Highcharts -->\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/web/resource/js/highcharts.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/web/resource/js/modules/data.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/web/resource/js/modules/exporting.js\"></script>\r\n");
      out.write("    <!-- DataTables -->\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/web/resource/js/datatables.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/views/consultaHistorica.jsp(238,35) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/resource/img/calender.png");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /WEB-INF/views/consultaHistorica.jsp(252,23) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/resource/img/calender.png");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/consultaHistorica.jsp(278,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/consultaHistorica.jsp(278,4) '${proveedores}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${proveedores}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/consultaHistorica.jsp(278,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("proveedores");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${proveedores.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${proveedores.proveedor}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/views/consultaHistorica.jsp(287,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/consultaHistorica.jsp(287,4) '${factores}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${factores}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/consultaHistorica.jsp(287,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("factores");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${factores.id_factor}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${factores.factor}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
    }
    return false;
  }
}
