/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.6
 * Generated at: 2016-11-14 22:53:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class welcome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/Users/APerez/Documents/workspace-for-sts/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/web/WEB-INF/lib/spring-webmvc-4.3.3.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1474314770000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.3.3.RELEASE.jar", Long.valueOf(1477501503367L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1477501505027L));
    _jspx_dependants.put("jar:file:/C:/Users/APerez/Documents/workspace-for-sts/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/web/WEB-INF/lib/spring-webmvc-4.3.3.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1474314770000L));
    _jspx_dependants.put("jar:file:/C:/Users/APerez/Documents/workspace-for-sts/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/web/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153403082000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>Welcome</title>\r\n");
      out.write("    <!-- Bootstrap -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css\">\r\n");
      out.write("\t<!-- JQuery UI -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css\">\r\n");
      out.write("\t<!-- Highcharts -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"/web/resource/css/highcharts.css\">\r\n");
      out.write("\t<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/web/resource/css/ie10-viewport-bug-workaround.css\">\r\n");
      out.write("    \r\n");
      out.write("\t<!-- JQuery & JQuery UI javascript-->\r\n");
      out.write("\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\r\n");
      out.write("  \t<script src=\"https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js\"></script>\r\n");
      out.write("  \t\r\n");
      out.write("    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->\r\n");
      out.write("    <!--[if lt IE 9]><script src=\"/web/resource/js/ie8-responsive-file-warning.js\"></script><![endif]-->\r\n");
      out.write("    <script src=\"/web/resource/js/ie-emulation-modes-warning.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js\"></script>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\t.st80{\r\n");
      out.write("\t\t\twidth: 80%;\r\n");
      out.write("\t\t\tmargin: 0 auto;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#proveedoresDePrecios, #curvasDeMercado, #nodosDeCurva{\r\n");
      out.write("\t\t\tpadding-top: 10px;\r\n");
      out.write("\t\t\tpadding-bottom: 10px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t/*#proveedoresDePrecios div.st80{\r\n");
      out.write("\t\t\theight: 100px;\r\n");
      out.write("\t\t}*/\r\n");
      out.write("\t\t#selProveedor{\r\n");
      out.write("\t\t\theight: 30px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#curvasDeMercado div.st80, #nodosDeCurva div.st80{\r\n");
      out.write("\t\t\tbackground-color: #F5F5F5;\r\n");
      out.write("\t\t\theight: 350px;\r\n");
      out.write("\t\t\toverflow-y: scroll;\r\n");
      out.write("\t\t\t/*margin-right: 100px;*/\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#curvasDeMercado div.list div, div.generateGraphics{\r\n");
      out.write("\t\t\tbackground-color: #4682B4;\r\n");
      out.write("\t\t\tcolor: #FFFFFF;\r\n");
      out.write("\t\t\tfont-weight: 600;\r\n");
      out.write("\t\t\tpadding: 10px 0 10px 10px;\r\n");
      out.write("    \t\tmargin: 10px 0;\r\n");
      out.write("    \t\tborder-radius: 5px;\r\n");
      out.write("    \t\tborder: 2px solid #4682B4;\r\n");
      out.write("    \t\ttransition: all 500ms ease;\r\n");
      out.write("\t\t}\t\r\n");
      out.write("\t\t#curvasDeMercado div.list div:hover, div.generateGraphics:hover{\r\n");
      out.write("\t\t\tbackground-color: #0c3a61;\r\n");
      out.write("\t\t\tborder: 2px solid #0c3a61;\r\n");
      out.write("\t\t\tcursor: pointer;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#curvasDeMercado div.list div.selected{\r\n");
      out.write("\t\t\tcolor: #4682B4;\r\n");
      out.write("\t\t\tbackground-color: #FFFFFF;\r\n");
      out.write("\t\t\tborder: 2px solid #4682B4;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#nodosDeCurva ul{\r\n");
      out.write("\t\t\tlist-style-type: none;\r\n");
      out.write("\t\t\tpadding-left: 10px;\r\n");
      out.write("    \t\tpadding-top: 10px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#nodosDeCurva ul li input[type=\"checkbox\"]{\r\n");
      out.write("\t\t\tmargin-right: 5px;\r\n");
      out.write("\t\t\tmargin-bottom: 3px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdiv.generateGraphics{\r\n");
      out.write("\t\t\twidth: 60%;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdiv.littleScreen div.generateGraphics{\r\n");
      out.write("\t\t\tdisplay: none;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdiv.bigScreen div.generateGraphics{\r\n");
      out.write("\t\t\tdisplay: block;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#graphicsTables table{\r\n");
      out.write("\t\t\tdisplay: none;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdiv.graphics div.chart{\r\n");
      out.write("\t\t\theight: 350px;\r\n");
      out.write("\t\t\tmargin-top: 30px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdiv.chart svg{\r\n");
      out.write("\t\t\theight: 100%;\r\n");
      out.write("\t\t\twidth: 100%;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdiv.col-sm-4 > div.st80 > p > input[type=\"text\"],\r\n");
      out.write("\t\tdiv.col-sm-4 > div.st80 > div > p > input[type=\"number\"]{\r\n");
      out.write("\t\t\twidth: 50%;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t/* RESPONSIVE CSS\r\n");
      out.write("\t\t-------------------------------------------------- */\r\n");
      out.write("\t\t@media only screen and (max-width: 480px), only screen and (max-device-width_ 480px){\r\n");
      out.write("\t\t\tdiv.bigScreen div.generateGraphics{\r\n");
      out.write("\t\t\t\tdisplay: none;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tdiv.littleScreen div.generateGraphics{\r\n");
      out.write("\t\t\t\tdisplay: block;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t@media (min-width: 768px) and (max-width: 1014px){\r\n");
      out.write("\t\t\tdiv.col-sm-4 > div.st80 > p > input[type=\"text\"],\r\n");
      out.write("\t\t\tdiv.col-sm-4 > div.st80 > div > p > input[type=\"number\"]{\r\n");
      out.write("\t\t\t\twidth: 75%;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tvar graphicsIds = [];\r\n");
      out.write("\t\tvar tableIds = [];\r\n");
      out.write("\t\tvar tableCounter = 0;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction drawGraphics(){\r\n");
      out.write("\t\t\ttableCounter = 0;\r\n");
      out.write("\t\t\t$.each(graphicsIds, function(id, item){\r\n");
      out.write("\t\t\t\tvar chart = new Highcharts.Chart({\r\n");
      out.write("\t                chart: {\r\n");
      out.write("\t                \trenderTo: item,\r\n");
      out.write("\t                    type: 'line',\r\n");
      out.write("\t                    borderWidth: 1,\r\n");
      out.write("\t                    plotBorderWidth: 2,\r\n");
      out.write("\t                    borderColor: '#a1a1a1',\r\n");
      out.write("\t                    borderRadius: 3,\r\n");
      out.write("\t                    marginLeft: 80\r\n");
      out.write("\t                },\r\n");
      out.write("\t                data: {\r\n");
      out.write("\t                    table: tableIds[tableCounter]\r\n");
      out.write("\t                },\r\n");
      out.write("\t                title: {\r\n");
      out.write("\t                    text: tableIds[tableCounter]\r\n");
      out.write("\t                },\r\n");
      out.write("\t                legend: {\r\n");
      out.write("\t                    enabled: false\r\n");
      out.write("\t                },\r\n");
      out.write("\t                xAxis: {\r\n");
      out.write("\t                    showLastLabel: true,\r\n");
      out.write("\t                    tickPixelInterval: 25,\r\n");
      out.write("\t                    type: 'datetime',\r\n");
      out.write("\t                    labels: {\r\n");
      out.write("\t                        format: '{value:%d-%m-%y}',\r\n");
      out.write("\t                        rotation: 90,\r\n");
      out.write("\t                        style: {\r\n");
      out.write("\t                            fontSize: '1.2em'\r\n");
      out.write("\t                        }\r\n");
      out.write("\t                    }\r\n");
      out.write("\t                },\r\n");
      out.write("\t                yAxis: {  \r\n");
      out.write("\t                    title: {\r\n");
      out.write("\t                        enabled: false\r\n");
      out.write("\t                    },\r\n");
      out.write("\t                    labels: {\r\n");
      out.write("\t                        format: '{value} %',\r\n");
      out.write("\t                        style: { fontSize: '1.2em' }\r\n");
      out.write("\t                    },\r\n");
      out.write("\t                    tickPixelInterval: 80\r\n");
      out.write("\t                },\r\n");
      out.write("\t                credits: {\r\n");
      out.write("\t                    enabled: false\r\n");
      out.write("\t                },\r\n");
      out.write("\t                plotOptions: {\r\n");
      out.write("\t                    series: {\r\n");
      out.write("\t                        dataLabels: {\r\n");
      out.write("\t                            enabled: true,\r\n");
      out.write("\t                            format: '{point.label}'\r\n");
      out.write("\t                        },\r\n");
      out.write("\t                        tooltip: {\r\n");
      out.write("\t                            valueSuffix: ' %'\r\n");
      out.write("\t                        }\r\n");
      out.write("\t                    }\r\n");
      out.write("\t                },\r\n");
      out.write("\t                tooltip: {\r\n");
      out.write("\t                    pointFormat: '<span style=\"color:{series.color}\">{series.name}</span>: <b>{point.y}</b> ({point.change}%)<br/>',\r\n");
      out.write("\t                    valueDecimals: 2\r\n");
      out.write("\t                }\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\ttableCounter += 1;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction Nodo(prov, id){\r\n");
      out.write("\t\t\tthis.prov = prov;\r\n");
      out.write("\t\t\tthis.id = id;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tNodo.prototype.equals = function(n){\r\n");
      out.write("\t\t\tif(this.prov != n.prov){ return false;}\r\n");
      out.write("\t\t\tif(this.id != n.id){ return false;}\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction SelectedNodos(){\r\n");
      out.write("\t\t\tthis.nodos = [];\r\n");
      out.write("\t\t\tthis.fechaI = \"\";\r\n");
      out.write("\t\t\tthis.fechaF = \"\";\r\n");
      out.write("\t\t\tthis.metodo = 0;\r\n");
      out.write("\t\t\tthis.noDias = 0;\r\n");
      out.write("\t\t\tthis.noDatos = 0;\r\n");
      out.write("\t\t\tthis.factorDD = 0;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tSelectedNodos.prototype.addNodo = function(nodo){\r\n");
      out.write("\t\t\tfor(var i = 0; i < this.nodos.length; i++ ){\r\n");
      out.write("\t\t\t\tif( this.nodos[i].equals(nodo) ) return false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tthis.nodos.push(nodo);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\tSelectedNodos.prototype.deleteNodo = function(nodo){\r\n");
      out.write("\t\t\tfor(var i = 0; i < this.nodos.length; i++ ){\r\n");
      out.write("\t\t\t\tif( this.nodos[i].equals(nodo) ){\r\n");
      out.write("\t\t\t\t\tthis.nodos.splice(i, 1);\r\n");
      out.write("\t\t\t\t\treturn true;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar sels = new SelectedNodos();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction updateSelected(elem){\r\n");
      out.write("\t\t\tvar idP = $('#selProveedor').val();\r\n");
      out.write("\t\t\tvar nodo = new Nodo(idP, elem.id); \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(elem.checked){ \r\n");
      out.write("\t\t\t\tsels.addNodo(nodo);\r\n");
      out.write("\t\t\t}else{ \r\n");
      out.write("\t\t\t\tsels.deleteNodo(nodo); \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction generateGraphics(){\r\n");
      out.write("\t\t\tsels.metodo = parseInt( $('input[name=method]:checked').val() );\r\n");
      out.write("\t\t\tif( $('#noDias').val() > 0 )\r\n");
      out.write("\t\t\t\tsels.noDias = parseInt( $('#noDias').val() );\r\n");
      out.write("\t\t\tif( $('#noDatos').val() )\r\n");
      out.write("\t\t\t\tsels.noDatos = parseInt( $('#noDatos').val() );\r\n");
      out.write("\t\t\tif( $('#factorDD').val() > 0 )\r\n");
      out.write("\t\t\t\tsels.factorDD = parseFloat( $('#factorDD').val() ); \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tconsole.log(sels);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tajaxGraphicsFunction();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction getCurvas(sel) {\r\n");
      out.write("\t\t\t$('#curvasDeMercado div.st80 div.list, #nodosDeCurva ul').fadeOut(\"slow\", function(){\r\n");
      out.write("\t\t\t\t$('#curvasDeMercado div.st80 div.list').html('');\r\n");
      out.write("\t\t\t\t$('#nodosDeCurva ul').html('');\r\n");
      out.write("\t\t\t\tajaxCurvaFunction(sel.value);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t    }\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction getNodos(sel){\r\n");
      out.write("\t\t\t$(sel).siblings().each(function(){\r\n");
      out.write("\t\t\t\tif( $(this).hasClass('selected') ){\r\n");
      out.write("\t\t\t\t\t$(this).toggleClass('selected');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(sel).toggleClass('selected');\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar id_prov = $('#selProveedor').val();\r\n");
      out.write("\t\t\t$('#nodosDeCurva ul').fadeOut(\"slow\", function(){\r\n");
      out.write("    \t\t\t$('#nodosDeCurva ul').html('');\r\n");
      out.write("    \t\t\tajaxNodoFunction(id_prov, sel.className, sel.attributes[\"name\"].value);\r\n");
      out.write("    \t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("    \tfunction ajaxCurvaFunction(id) {\r\n");
      out.write("        \t$.ajax({\r\n");
      out.write("            \turl : 'curvas/'+id,\r\n");
      out.write("            \tcache : false,\r\n");
      out.write("                contentType : 'application/json; charset=utf-8',\r\n");
      out.write("                type : 'GET',\r\n");
      out.write("            \tsuccess : function(data) {\r\n");
      out.write("                \tvar items = [];\r\n");
      out.write("                \t\r\n");
      out.write("                \t$.each(data, function(id, option){\r\n");
      out.write("                \t\titems.push(\"<div class='\" + option.id_curva + \"' name='\" \r\n");
      out.write("               \t\t\t\t + option.columna + \"' onclick='getNodos(this);'>\" + option.descripcion + \"</div>\");\r\n");
      out.write("                \t});\r\n");
      out.write("                \t\r\n");
      out.write("                \t$('#curvasDeMercado div.st80 div.list').html(items.join(''));\r\n");
      out.write("                \t$('#curvasDeMercado div.st80 div.list').fadeIn();\r\n");
      out.write("            \t}\r\n");
      out.write("        \t});\r\n");
      out.write("    \t}\r\n");
      out.write("    \t\r\n");
      out.write("    \tfunction ajaxNodoFunction(id_prov, id_curva, col){\r\n");
      out.write("    \t\t$.ajax({\r\n");
      out.write("            \turl : 'nodos/ByCriteria;id_proveedor='+id_prov+';col='+col+';',\r\n");
      out.write("            \tcache : false,\r\n");
      out.write("                contentType : 'application/json; charset=utf-8',\r\n");
      out.write("                type : 'GET',\r\n");
      out.write("            \tsuccess : function(data) {\r\n");
      out.write("                \tvar items = [];\r\n");
      out.write("                \t\r\n");
      out.write("                \t$.each(data, function(id, option){\r\n");
      out.write("                \t\titems.push(\"<li><input onclick='updateSelected(this);' type='checkbox' value='\" + option.factor \r\n");
      out.write("                \t\t\t\t + \"' id='\"+option.id_Factor + /*\"' name='\" + option.columna + */\"'>\" \r\n");
      out.write("                \t\t\t\t + option.factor + \"</li>\");\r\n");
      out.write("                \t});\r\n");
      out.write("                \t\r\n");
      out.write("                \t$('#nodosDeCurva ul').html(items.join(''));\r\n");
      out.write("                \tfor(var i = 0; i < sels.nodos.length; i++){ \r\n");
      out.write("                \t\tif( $('#'+sels.nodos[i].id).length > 0 ){ \r\n");
      out.write("                \t\t\tif( $('#selProveedor').val() == sels.nodos[i].prov ){ \r\n");
      out.write("                \t\t\t\t$('#'+sels.nodos[i].id).prop(\"checked\", true);\r\n");
      out.write("                \t\t\t}\r\n");
      out.write("                \t\t}\r\n");
      out.write("                \t}\r\n");
      out.write("                \t$('#nodosDeCurva ul').fadeIn();\r\n");
      out.write("            \t}\r\n");
      out.write("        \t});\r\n");
      out.write("    \t}\r\n");
      out.write("    \t\r\n");
      out.write("    \tfunction ajaxGraphicsFunction(){\r\n");
      out.write("    \t\t$.ajax({\r\n");
      out.write("            \turl : 'graficas/',\r\n");
      out.write("            \tcache : false,\r\n");
      out.write("                contentType : 'application/json; charset=utf-8',\r\n");
      out.write("                dataType : 'json',\r\n");
      out.write("                data : JSON.stringify(sels),\r\n");
      out.write("                type : 'POST',\r\n");
      out.write("            \tsuccess : function(data) {\r\n");
      out.write("            \t\tvar tables = [];\r\n");
      out.write("            \t\tvar graphicDivs = [];\r\n");
      out.write("            \t\ttableIds.length = 0;\r\n");
      out.write("            \t\tgraphicsIds.length = 0;\r\n");
      out.write("            \t\t\r\n");
      out.write("            \t\t$.each(data, function(id, option){\r\n");
      out.write("            \t\t\tvar divs = \"<div class='col-sm-6 col-xs-12 chart' id='\"\r\n");
      out.write("            \t\t\t         + option.proveedor + option.factor + \"'></div>\";\r\n");
      out.write("            \t\t\t\r\n");
      out.write("            \t\t\tvar table = \"<table id='\" + option.proveedor + \"-\" + option.factor + \"' class='graphicTable'>\"\r\n");
      out.write("            \t\t\t          + \"<thead>\"\r\n");
      out.write("            \t\t\t          + \"<tr><th></th><th>\" + option.proveedor + \"-\" + option.factor + \"</th></tr>\"\r\n");
      out.write("            \t\t\t          + \"</thead><tbody>\";\r\n");
      out.write("            \t\t\t          \r\n");
      out.write("     \t\t\t        tableIds.push(option.proveedor + \"-\" + option.factor);\r\n");
      out.write("               \t\t\tgraphicsIds.push(option.proveedor + option.factor);\r\n");
      out.write("               \t\t\t\r\n");
      out.write("\t\t\t\t\t\t$.each(option.listOfValues, function(id, val){\r\n");
      out.write("\t\t\t\t\t\t\ttable += \"<tr><th>\" + val.date +\"</th><td>\" + val.doubleValue + \"</td></tr>\";\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\ttable += \"</tbody></table>\";\r\n");
      out.write("\t\t\t\t\t\ttables.push(table);\r\n");
      out.write("\t\t\t\t\t\tgraphicDivs.push(divs);\r\n");
      out.write("            \t\t});\r\n");
      out.write("            \t\tgraphicDivs = graphicDivs.concat(tables);\r\n");
      out.write("            \t\t$('#graphicsTables').html(graphicDivs.join(''));\r\n");
      out.write("            \t\tdrawGraphics();\r\n");
      out.write("            \t},\r\n");
      out.write("            \terror : function(e){\r\n");
      out.write("            \t\tconsole.log(\"ERROR: \", e);\r\n");
      out.write("            \t}\r\n");
      out.write("    \t\t});\r\n");
      out.write("    \t}\r\n");
      out.write("    \t\r\n");
      out.write("    \t$(function(){\r\n");
      out.write("    \t\t$(\"input[name=method]\").on( \"change\", function() {\r\n");
      out.write("                var method = parseInt($(this).val());\r\n");
      out.write("                switch(method) {\r\n");
      out.write("                    case 1:\r\n");
      out.write("                        $(\".method2\").hide();\r\n");
      out.write("                        $(\".method1\").show(\"slow\");\r\n");
      out.write("                        break;\r\n");
      out.write("                    case 2:\r\n");
      out.write("                        $(\".method1\").hide();\r\n");
      out.write("                        $(\".method2\").show(\"slow\");\r\n");
      out.write("                        break;\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("    \t\t\r\n");
      out.write("\t\t\t$(\"#fechaI\").datepicker({\r\n");
      out.write("\t\t\t\tshowOn          : \"button\",\r\n");
      out.write("                buttonImage     : \"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\",\r\n");
      out.write("                buttonImageOnly : true,\r\n");
      out.write("                buttonText      : \"Seleccione una fecha\",\r\n");
      out.write("                changeMonth     : true,\r\n");
      out.write("                changeYear      : true,\r\n");
      out.write("                yearRange       : \"-15:+0\",\r\n");
      out.write("                dateFormat      : 'mm-dd-yy',\r\n");
      out.write("                showAnim        : 'slideDown',\r\n");
      out.write("                beforeShow      : function(){$(\".ui-datepicker\").css('font-size',10);},\r\n");
      out.write("                onSelect\t\t: function(){sels.fechaI = $(this).val();}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#fechaF\").datepicker({\r\n");
      out.write("\t\t\t\tshowOn          : \"button\",\r\n");
      out.write("\t\t\t\tbuttonImage     : \"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\",\r\n");
      out.write("                buttonImageOnly : true,\r\n");
      out.write("                buttonText      : \"Seleccione una fecha\",\r\n");
      out.write("                changeMonth     : true,\r\n");
      out.write("                changeYear      : true,\r\n");
      out.write("                yearRange       : \"-15:+0\",\r\n");
      out.write("                dateFormat      : 'mm-dd-yy',\r\n");
      out.write("                showAnim        : 'slideDown',\r\n");
      out.write("                beforeShow      : function(){$(\".ui-datepicker\").css('font-size',10);},\r\n");
      out.write("                onSelect\t\t: function(){sels.fechaF = $(this).val();}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<section>\r\n");
      out.write("\t\t<div class=\"container jumbotron\">\r\n");
      out.write("\t\t\t<h1> Reporte de Volatilidades </h1>\r\n");
      out.write("\t\t</div><!-- .container end -->\r\n");
      out.write("\t</section>\r\n");
      out.write("\t\r\n");
      out.write("\t<section class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-sm-4 col-xs-12\"><div class=\"st80\">\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<label for=\"fechaI\">Fecha inicial</label><br>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"fechaI\" >\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<label for=\"fechaF\">Fecha final</label><br>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"fechaF\" >\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div></div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"col-sm-4 col-xs-12\"><div class=\"st80\">\r\n");
      out.write("\t\t\t\t<p><b>Seleccione un método</b></p>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("                <p> \r\n");
      out.write("                \t<input id=\"method1\" type=\"radio\" name=\"method\" value=\"1\" />\r\n");
      out.write("                \t<label for=\"method1\">Método simple</label>\r\n");
      out.write("                </p>\r\n");
      out.write("                \r\n");
      out.write("                <p>\r\n");
      out.write("                 \t<input id=\"method2\" type=\"radio\" name=\"method\" value=\"2\"/>\r\n");
      out.write("                 \t<label for=\"method2\">EWMA</label> \r\n");
      out.write("                 </p>\r\n");
      out.write("\t\t\t</div></div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"col-sm-4 col-xs-12\"><div class=\"st80\">\r\n");
      out.write("\t\t\t\t<div class=\"method1\" style=\"display:none\">\r\n");
      out.write("\t\t\t\t\t<p><label for=\"noDias\">Número de días</label><br>\r\n");
      out.write("\t\t\t\t\t<input type=\"number\" id=\"noDias\" placeholder=\"0\" min=\"1\" max=\"600\"></p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"method2\" style=\"display:none\">\r\n");
      out.write("\t\t\t\t\t<p><label for=\"noDatos\">Número de datos</label><br>\r\n");
      out.write("\t\t\t\t\t<input type=\"number\" id=\"noDatos\" placeholder=\"0\" min=\"1\" max=\"600\"></p>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<p><label for=\"factorDD\">Factor de Decaimiento</label><br>\r\n");
      out.write("\t\t\t\t\t<input type=\"number\" id=\"factorDD\" placeholder=\"0\" min=\"0.001\" max=\"0.999\"></p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div></div>\r\n");
      out.write("\t\t</div><!-- .row end -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"row bigScreen\">\r\n");
      out.write("\t\t\t<div id=\"proveedoresDePrecios\" class=\"col-sm-4 col-xs-12\"><div class=\"st80\">\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<select id=\"selProveedor\" onchange=\"getCurvas(this);\">\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"generateGraphics\" onclick=\"generateGraphics();\">Enviar</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div></div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"curvasDeMercado\" class=\"col-sm-4 col-xs-12\"><div class=\"st80\"><div class=\"list\"></div></div></div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"nodosDeCurva\" class=\"col-sm-4 col-xs-12\"><div class=\"st80\"><ul></ul></div></div>\r\n");
      out.write("\t\t</div><!-- .row end -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"row littleScreen\">\r\n");
      out.write("\t\t\t<div class=\"col-sm-4 col-xs-12\"></div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-4 col-xs-12\"></div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-4 col-xs-12\"><div class=\"st80\">\r\n");
      out.write("\t\t\t\t<div class=\"generateGraphics\" onclick=\"generateGraphics()\">Enviar</div>\r\n");
      out.write("\t\t\t</div></div>\r\n");
      out.write("\t\t</div><!-- .row end -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"graphicsTables\" class=\"row graphics\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section><!-- .container end -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Bootstrap core JavaScript\r\n");
      out.write("\t================================================== -->\r\n");
      out.write("    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->\r\n");
      out.write("    <script src=\"/web/resource/js/ie10-viewport-bug-workaround.js\"></script>\r\n");
      out.write("    <!-- Highcharts -->\r\n");
      out.write("    <script src=\"/web/resource/js/highcharts.js\"></script>\r\n");
      out.write("    <script src=\"/web/resource/js/modules/data.js\"></script>\r\n");
      out.write("    <script src=\"/web/resource/js/modules/exporting.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/views/welcome.jsp(400,35) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/resource/img/calender.png");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /WEB-INF/views/welcome.jsp(414,23) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/resource/img/calender.png");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/welcome.jsp(482,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/welcome.jsp(482,5) '${proveedores}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${proveedores}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/welcome.jsp(482,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("proveedores");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${proveedores.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${proveedores.proveedor}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }
}
